-- Urban Drop 4 cloud database
create table if not exists public.products (
  id text primary key,
  name text not null,
  price numeric not null default 0,
  description text default '',
  image_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  city text not null,
  address text not null,
  delivery text default '',
  total numeric not null default 0,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'جديد',
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.products enable row level security;
alter table public.settings enable row level security;
alter table public.orders enable row level security;

create or replace function public.ud4_is_admin()
returns boolean language sql stable as $$
  select true;
$$;

drop policy if exists "products_public_read" on public.products;
drop policy if exists "products_admin_insert" on public.products;
drop policy if exists "products_admin_update" on public.products;
drop policy if exists "products_admin_delete" on public.products;
create policy "products_public_read" on public.products for select using (true);
create policy "products_admin_insert" on public.products for insert with check (true);
create policy "products_admin_update" on public.products for update using (true) with check (true);
create policy "products_admin_delete" on public.products for delete using (true);

drop policy if exists "settings_public_read" on public.settings;
drop policy if exists "settings_admin_insert" on public.settings;
drop policy if exists "settings_admin_update" on public.settings;
drop policy if exists "settings_admin_delete" on public.settings;
create policy "settings_public_read" on public.settings for select using (true);
create policy "settings_admin_insert" on public.settings for insert with check (true);
create policy "settings_admin_update" on public.settings for update using (true) with check (true);
create policy "settings_admin_delete" on public.settings for delete using (true);

drop policy if exists "orders_public_insert" on public.orders;
drop policy if exists "orders_admin_read" on public.orders;
drop policy if exists "orders_admin_update" on public.orders;
drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_public_insert" on public.orders for insert with check (true);
create policy "orders_admin_read" on public.orders for select using (true);
create policy "orders_admin_update" on public.orders for update using (true) with check (true);
create policy "orders_admin_delete" on public.orders for delete using (true);

insert into public.settings (id,data) values (1,'{"brand":"URBAN DROP 4","tagline":"PERFUME & STYLE","topText":"🚚 توصيل لجميع أنحاء المغرب","payment":"💵 الدفع عند الاستلام","heroSmall":"NEW COLLECTION · 2026","heroTitle":"عطرك.|ستايلك.","heroDesc":"اكتشف مجموعتنا المختارة من العطور الفاخرة، بتجربة سهلة وتوصيل لجميع أنحاء المغرب.","heroButton":"اكتشف العطور ←","productsTitle":"الأكثر طلباً","accent":"#d4af37","bg":"#090909","font":"Arial, Tahoma, sans-serif","bgImage":"","heroVisible":true}'::jsonb)
on conflict (id) do nothing;

insert into public.products (id,name,price,description,image_url) values
('p1','NOIR INTENSE',249,'عطر رجالي أنيق بحضور قوي ولمسة عصرية.',''),
('p2','BLUE NIGHT',229,'عطر منعش مناسب للاستعمال اليومي والمناسبات.',''),
('p3','URBAN GOLD',279,'تركيبة فاخرة لمن يبحث عن حضور مميز.',''),
('p4','PURE MUSK',219,'رائحة ناعمة ونظيفة بلمسة أنيقة.',''),
('p5','BLACK OUD',299,'عود فاخر برائحة عميقة وثابتة.',''),
('p6','URBAN FRESH',239,'انتعاش خفيف وأنيق للاستخدام اليومي.','')
on conflict (id) do nothing;

insert into storage.buckets (id,name,public) values ('ud4-products','ud4-products',true)
on conflict (id) do update set public=true;
drop policy if exists "ud4_images_public_read" on storage.objects;
drop policy if exists "ud4_images_admin_insert" on storage.objects;
drop policy if exists "ud4_images_admin_update" on storage.objects;
drop policy if exists "ud4_images_admin_delete" on storage.objects;
create policy "ud4_images_public_read" on storage.objects for select using (bucket_id='ud4-products');
create policy "ud4_images_admin_insert" on storage.objects for insert with check (bucket_id='ud4-products');
create policy "ud4_images_admin_update" on storage.objects for update using (bucket_id='ud4-products') with check (bucket_id='ud4-products');
create policy "ud4_images_admin_delete" on storage.objects for delete using (bucket_id='ud4-products');

-- Customer authentication / order ownership (optional for anonymous checkout)
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;
drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert" on public.orders for insert with check (user_id is null or auth.uid() = user_id);
drop policy if exists "orders_customer_read" on public.orders;
create policy "orders_customer_read" on public.orders for select using (auth.uid() = user_id);


-- Customer order cancellation: customers can cancel only their own orders
-- while the order is still new or being processed.
create or replace function public.ud4_cancel_order(p_order_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return false;
  end if;

  update public.orders
  set status = 'ملغى'
  where id = p_order_id
    and user_id = auth.uid()
    and status in ('جديد', 'قيد المعالجة');

  return found;
end;
$$;

revoke all on function public.ud4_cancel_order(bigint) from public;
grant execute on function public.ud4_cancel_order(bigint) to authenticated;
